# Generated by Django 3.0.6 on 2020-06-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imessage',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
