# Generated by Django 3.0.6 on 2020-05-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='username',
            new_name='user',
        ),
    ]
