# Generated by Django 3.0.6 on 2020-05-31 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200531_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
